### PR TITLE
Fixes #2306 - Reporting content screen not being displayed

### LINKED ISSUE #2306: Reporting content doesn't present report screen
https://github.com/element-hq/element-x-ios-rageshakes/issues/1292

Reporting content from the timeline doesn't present the report content screen. Subsequent transitions fails because the state is the same. 

This is a regression introduced with the `RoomScreenInteractionHandler` and it's basically a typo.

### PR DESCRIPTION
**Pull request by stefanceriu**

### CODE REVIEW

**Comment by Velin92** [comment]
what is the actual change of the PR? so far seems to be only a rename of the stack coordinator?

File: ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift [hunk 1]
```diff
@@ -646,8 +646,8 @@ class RoomFlowCoordinator: FlowCoordinatorProtocol {
             }
             .store(in: &cancellables)
         
-        navigationStackCoordinator.setRootCoordinator(coordinator)
-        navigationStackCoordinator.setSheetCoordinator(navigationStackCoordinator) { [weak self] in
+        stackCoordinator.setRootCoordinator(coordinator)
+        navigationStackCoordinator.setSheetCoordinator(stackCoordinator) { [weak self] in
```
Comment (stefanceriu) [inline ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift:650]: @Velin92 this bit here ^ is key, where `navigationStackCoordinator` was used to present itself

**Review by Velin92 — APPROVED** [review]
