### PR TITLE
Fixes #3126 - Prevent identity confirmation from blocking the user's progress after registering through OIDC

### LINKED ISSUE #3126: Device verification appears after a fresh new registration
### Steps to reproduce

1. Select a HS with a MAS accepting registration (ask if you do not know one)
2. Create an account

<details>
<summary>The device verification unexpectly appears</summary>

</details>

#### What did you expect?
Enteting within the app and seeing an empty room list.

#### What happened instead?
I had to reset the identity on a fresh new account

### Your phone model

_No response_

### Operating system version

_No response_

### Application version

_No response_

### Homeserver

_No response_

### Will you send logs?

Yes

### PR DESCRIPTION
**Pull request by stefanceriu**
- happened because `hasRunIdentityConfirmationOnboarding` is false while the verification state is still `.unknown`
- verification eventually changes to `.verified` but the flow coordinator doesn't catch up on it and blocks the flow

### CODE REVIEW

File: ElementX/Sources/FlowCoordinators/OnboardingFlowCoordinator.swift [hunk 1]
```diff
@@ -43,6 +43,7 @@ class OnboardingFlowCoordinator: FlowCoordinatorProtocol {
     
     enum Event: EventType {
         case next
+        case nextSkippingIdentityConfimed
```
Comment (pixlwave) [inline ElementX/Sources/FlowCoordinators/OnboardingFlowCoordinator.swift:46]: Can we use this on our debug skip button too? 😇

File: ElementX/Sources/FlowCoordinators/OnboardingFlowCoordinator.swift [hunk 2]
```diff
@@ -223,7 +238,25 @@ class OnboardingFlowCoordinator: FlowCoordinatorProtocol {
...
+        // If the verification state is still unknown wait for it to resolve
+        // and just move on to the next steps if verified
+        var verificationStateCancellable: AnyCancellable?
+        if userSession.sessionSecurityStatePublisher.value.verificationState == .unknown {
+            verificationStateCancellable = userSession.sessionSecurityStatePublisher
+                .map(\.verificationState)
+                .removeDuplicates()
+                .sink { [weak self] value in
+                    if value == .verified {
+                        self?.stateMachine.tryEvent(.nextSkippingIdentityConfimed)
```
Comment (pixlwave) [inline ElementX/Sources/FlowCoordinators/OnboardingFlowCoordinator.swift:250]: Do we need to set the app setting to true here too?

File: ElementX/Sources/FlowCoordinators/OnboardingFlowCoordinator.swift [hunk 3]
```diff
@@ -223,7 +238,25 @@ class OnboardingFlowCoordinator: FlowCoordinatorProtocol {
...
+                    } else {
+                        verificationStateCancellable = nil
+                    }
+                }
+        }
+        
+        presentCoordinator(coordinator) { [verificationStateCancellable] in
+            verificationStateCancellable?.cancel()
```
Comment (pixlwave) [inline ElementX/Sources/FlowCoordinators/OnboardingFlowCoordinator.swift:258]: Wait, if this is captured, then setting it to nil above won’t do anything right? As we push the next screens onto the stack.

File: ElementX/Sources/FlowCoordinators/OnboardingFlowCoordinator.swift (hunk 2 above)
Comment (stefanceriu) [reply ElementX/Sources/FlowCoordinators/OnboardingFlowCoordinator.swift:250]: Good point!

File: ElementX/Sources/FlowCoordinators/OnboardingFlowCoordinator.swift (hunk 3 above)
Comment (stefanceriu) [reply ElementX/Sources/FlowCoordinators/OnboardingFlowCoordinator.swift:258]: Same here!
