### PR TITLE
Make sure introspections are used on iOS 18.

### LINKED ISSUE #3244: iOS 18 - Can't log in to OIDC server
### Steps to reproduce

Hi, on the iOS 18 RC I am unable to log into my homeserver that supports OIDC. I believe it is related to #1936 

Here is a screen recording of my latest attempt:

https://github.com/user-attachments/assets/572a59c7-0cdb-49e0-a40c-324d22c28224

Let me know if there's any other information that you need.

#### What did you expect?
to get a webview or "Element X wants to use Safari to log in" prompt
#### What happened instead?
nothing.

### Your phone model

iPhone 13 Pro Max

### Operating system version

iOS 18.0 (22A3354) RC

### Application version

Version 1.7.5 (121) from testflight

### Homeserver

devhack.net

### Will you send logs?

Yes

### PR DESCRIPTION
**Pull request by pixlwave**
Requires https://github.com/element-hq/compound-ios/pull/104 (and an update to Compound).

Fixes #3244.

### CODE REVIEW

File: ElementX/Sources/Other/Extensions/PlatformViewVersionPredicate.swift [hunk 1]
```diff
@@ -5,30 +5,23 @@
...
-import UIKit
-
+import SwiftUI
 import SwiftUIIntrospect
 
-extension PlatformViewVersionPredicate<WindowType, UIWindow> {
-    static var supportedVersions: Self {
-        .iOS(.v16, .v17)
-    }
-}
```
Comment (pixlwave) [inline ElementX/Sources/Other/Extensions/PlatformViewVersionPredicate.swift:16]: This one is provided by Compound now.

**Review by Velin92 — APPROVED** [review]
