### PR TITLE
Download SAS Strings Tool + Localised SAS emojis

### LINKED ISSUE #2402: Device verification: Emoji names are not translated
### Steps to reproduce

1. Configure the app to use another language than English
2. Log in the app
3. Start verification with another matrix client
4. The emoji names in the verification screen is in English instead of using the app language you selected

#### What did you expect?
Emoji names should be translated

#### What happened instead?
Emoji are in English

IMG_9648

### Your phone model

_No response_

### Operating system version

_No response_

### Application version

_No response_

### Homeserver

_No response_

### Will you send logs?

No

### PR DESCRIPTION
**Pull request by Velin92**
fixes #2402 

the new tool can called by using the `swift run tools generate-sas (--verbose/-v)` command

### CODE REVIEW

File: ElementX/Sources/Services/SessionVerification/SessionVerificationControllerProxyProtocol.swift [hunk 1]
```diff
@@ -38,6 +38,10 @@ enum SessionVerificationControllerProxyCallback {
 struct SessionVerificationEmoji: Hashable {
     let symbol: String
     let description: String
+    
+    var localizedDescription: String {
+        SASL10n.localizedDescription(for: description)
+    }
```
Comment (stefanceriu) [inline ElementX/Sources/Services/SessionVerification/SessionVerificationControllerProxyProtocol.swift:44]: Noice! 👍

File: Tools/Sources/GenerateSAS.swift [hunk 2]
```diff
@@ -0,0 +1,114 @@
...
+    static var configuration = CommandConfiguration(abstract: "A tool to download and generate SAS localization strings")
+    private static let defaultLanguage = "en"
+    
+    @Flag(name: .shortAndLong, help: "Increase output verbosity.")
+    var verbose = false
+
+    func run() throws {
+        let baseURL = URL(string: "https://raw.githubusercontent.com/matrix-org/matrix-spec/main/data-definitions/sas-emoji.json")!
+        
+        if verbose {
```
Comment (stefanceriu) [inline Tools/Sources/GenerateSAS.swift:14]: Can we please extract this verbose check into a separate `printIfVerbose` function or something?

File: Tools/Sources/GenerateSAS.swift [hunk 3]
```diff
@@ -0,0 +1,114 @@
...
+            print("Failed to download or parse JSON.")
+            return
+        }
+        
+        if verbose {
+            print("Json data:")
+            print(json)
+        }
+        
+        print()
```
Comment (stefanceriu) [inline Tools/Sources/GenerateSAS.swift:32]: What's this one about?

File: Tools/Sources/GenerateSAS.swift [hunk 4]
```diff
@@ -0,0 +1,114 @@
...
+        
+        print("Writing file \(filePath.path)")
+        
+        if verbose {
+            print("With")
+            print(dict)
+        }
+        
+        do {
+            // This will fail is the .lproj dir does not exist already, which is fine since we don't want to add translations for unsupported languages.
```
Comment (stefanceriu) [inline Tools/Sources/GenerateSAS.swift:95]:
```suggestion
            // This will fail if the .lproj dir does not exist already, which is fine since we don't want to add translations for unsupported languages.
```

**Review by stefanceriu — APPROVED** [review]
Very nice!
