### PR TITLE
Fixes #1911 - Automatically focus the composer when a hardware keyboa…

### LINKED ISSUE #1911: Autofocus composer field when changing room on Desktop
### Steps to reproduce

This is probably specific to running under macOS as an iPad app, but it's annoying:

1. Change room in the room list
2. Start typing in the room
3. Discover the composer isn't focused
4. Manually click on composer every time you change room.

#### What did you expect?

Autofocus composer

#### What happened instead?

No focus

### Your phone model

MBP

### Operating system version

Ventura

### Application version

410

### Homeserver

_No response_

### Will you send logs?

No

### PR DESCRIPTION
**Pull request by stefanceriu**
…rds is connected

### CODE REVIEW

File: ElementX/Sources/Screens/ComposerToolbar/ComposerToolbarViewModel.swift [hunk 1]
```diff
@@ -361,6 +364,22 @@ final class ComposerToolbarViewModel: ComposerToolbarViewModelType, ComposerTool
...
+        if GCKeyboard.coalesced != nil {
+            state.bindings.composerFocused = true
+        }
+        
+        NotificationCenter.default.addObserver(self, selector: #selector(hardwareKeyboardDidConnect), name: .GCKeyboardDidConnect, object: nil)
+        #endif
+    }
+    
+    @objc private func hardwareKeyboardDidConnect(_ notification: Notification) {
+        MXLog.error("Hardware keyboard did connect")
```
Comment (pixlwave) [inline ElementX/Sources/Screens/ComposerToolbar/ComposerToolbarViewModel.swift:380]: `.info` perhaps?

**Review by pixlwave — APPROVED** [review]

File: ElementX/Sources/Screens/ComposerToolbar/ComposerToolbarViewModel.swift (hunk 1 above)
Comment (stefanceriu) [reply ElementX/Sources/Screens/ComposerToolbar/ComposerToolbarViewModel.swift:380]: What, you don't want the logs to scream at you that a keyboard has been connected? 😅
