### PR TITLE
Public room search tweaks

### LINKED ISSUE #2744: Bugs for Public Room Search
### Steps to reproduce

- Please remove the "Join Room" button.
- Remove the line at the bottom.
- Show an empty search result.

### Your phone model

_No response_

### Operating system version

_No response_

### Application version

_No response_

### Homeserver

_No response_

### Will you send logs?

Yes

### PR DESCRIPTION
**Pull request by pixlwave**
- Remove the "Join" button.
- Hide the extra bottom separator.
- Show an empty search result.
- Fix a bug where we would paginate and search simultaneously.

Closes #2744.

### CODE REVIEW

File: ElementX/Sources/Screens/RoomDirectorySearchScreen/View/RoomDirectorySearchScreen.swift [hunk 1]
```diff
@@ -34,13 +34,20 @@ struct RoomDirectorySearchScreen: View {
...
+                            emptyRectangle
+                                .onAppear {
+                                    context.send(viewAction: .reachedBottom)
+                                }
                         }
-                        
-                        emptyRectangle
-                            .onAppear {
-                                context.send(viewAction: .reachedBottom)
-                            }
```
Comment (pixlwave) [inline ElementX/Sources/Screens/RoomDirectorySearchScreen/View/RoomDirectorySearchScreen.swift:42]: This needed to be in the else, otherwise when you started a search, the results would be cleared, the footer would become visible and it would simultaneously trigger a pagination.

Comment (Velin92) [reply ElementX/Sources/Screens/RoomDirectorySearchScreen/View/RoomDirectorySearchScreen.swift:42]: maybe let's add this as a comment

**Review by Velin92 — APPROVED** [review]
LGTM

File: ElementX/Sources/Screens/RoomDirectorySearchScreen/View/RoomDirectorySearchScreen.swift (hunk 1 above)
Comment (pixlwave) [reply ElementX/Sources/Screens/RoomDirectorySearchScreen/View/RoomDirectorySearchScreen.swift:42]: Oh yeah good shout.
