### PR TITLE
LocationSharingScreen: fix indefinite loading on the center to location button in non picker mode

### LINKED ISSUE #5462: [Task] iOS: Pending location when permissions are Ask Next Time Or When I Share
1. Alice starts sharing location.
2. Bob's location permissions are set to _Ask Next Time Or When I Share_
3. Bob taps on the timeline to open the map.

Expected: Bob sees the current location button at the top right of the map, and when tapping is asked to give location permissions.
Actual: There is a spinner at the place of the current location button which does not seem to go away.

Image

### PR DESCRIPTION
**Pull request by Velin92**
In picker mode since `showAndFollow` is the default state and the permissions are asked immediately to the user we display a spinner in the center to location button while the user grants permission or if they are granted, while the system gives the first user position.

In other modes however, permissions are not asked immediately, and would only be asked if the user wants the map to center on his own location, so we don't need to be so strict with the loading check, so we only show a loader if permissions ARE granted AND the location has not been loaded yet.

fixes #5462

### CODE REVIEW

**Review by stefanceriu — APPROVED** [review]
Alrighty, I'll trust you on this one 🚀

File: UnitTests/Sources/LocationSharingScreenViewModelTests.swift [hunk 1]
```diff
@@ -124,6 +124,61 @@ final class LocationSharingScreenViewModelTests {
...
+        let aliceShare = makeLiveLocationShare(userID: "@alice:matrix.org")
+        let sender = TimelineItemSender(id: "@alice:matrix.org", displayName: "Alice")
+        let liveLocationsSubject = CurrentValueSubject<[LiveLocationShare], Never>([aliceShare])
+        setupViewModelForViewLive(sender: sender, initialShare: aliceShare, liveLocationsSubject: liveLocationsSubject)
+        context.isLocationAuthorized = nil
+        context.hasLoadedUserLocation = false
+        #expect(!context.viewState.isLocationLoading)
+    }
+    
+    func isLocationLoadingInNonPickerModeWithAuthorizationGiven() {
```
Comment (pixlwave) [inline UnitTests/Sources/LocationSharingScreenViewModelTests.swift:173]: Not a review, just skimmed and I think this one is missing an `@Test`.

Comment (Velin92) [reply UnitTests/Sources/LocationSharingScreenViewModelTests.swift:173]: whoopsie doopsie
