### PR TITLE
Make sure the BugReportScreen allows the user to retry if sending fails.

### LINKED ISSUE #2974: If a rageshake upload fails, there is no way to retry
### Steps to reproduce

1. try to rageshake on bad connectivity
2. the req fails
3. the UI is stuck with “send” greyed out, and you can’t select the the bug report text to copy it
4. No way to retry; you have to hit back and try again and then manually retype the report

### Outcome

see above

### Your phone model

_No response_

### Operating system version

_No response_

### Application version

631

### Homeserver

_No response_

### Will you send logs?

Yes

### PR DESCRIPTION
**Pull request by pixlwave**
Fixes #2974

### CODE REVIEW

File: UnitTests/Sources/BugReportScreenViewModelTests.swift [hunk 1]
```diff
@@ -120,17 +123,11 @@ class BugReportViewModelTests: XCTestCase {
...
         try await deferred.fulfill()
         
         XCTAssert(mockService.submitBugReportProgressListenerCallsCount == 1)
-        XCTAssertEqual(mockService.submitBugReportProgressListenerReceivedArguments?.bugReport.userID, "@mock.client.com")
-        XCTAssertEqual(mockService.submitBugReportProgressListenerReceivedArguments?.bugReport.deviceID, nil)
-        XCTAssertEqual(mockService.submitBugReportProgressListenerReceivedArguments?.bugReport.text, "")
-        XCTAssertEqual(mockService.submitBugReportProgressListenerReceivedArguments?.bugReport.includeLogs, true)
-        XCTAssertEqual(mockService.submitBugReportProgressListenerReceivedArguments?.bugReport.canContact, false)
-        XCTAssertEqual(mockService.submitBugReportProgressListenerReceivedArguments?.bugReport.githubLabels, [])
-        XCTAssertEqual(mockService.submitBugReportProgressListenerReceivedArguments?.bugReport.files, [])
```
Comment (pixlwave) [inline UnitTests/Sources/BugReportScreenViewModelTests.swift:134]: These didn't really seem necessary for testing what happens when sending fails as they're already checked on the success path.

**Review by Velin92 — APPROVED** [review]
